[project]
name = "image-captioning-blv-people"
version = "0.0.1"
requires-python = ">=3.11,<3.12"
dependencies = [
    "requests",
    "pillow",
    "transformers==4.51.0",
    "accelerate",
    "huggingface-hub",
    "numpy",
    "jupyterlab",
    "ipywidgets",
    "tqdm",
    "pandas",
    "jupyter-black",
    "ollama",
    "albumentations",
    "matplotlib",
    "opencv-python",
    "scipy",
    "einops",
    "bitsandbytes; sys_platform == 'linux'",
    "seaborn",
    "openai",
    "evaluate",
    "nltk",
    "rouge-score",
    "pydantic",
    "sentence-transformers",
    "scikit-learn",
    "pingouin",
    "protobuf",
    "sentencepiece",
    "tiktoken",
    "pycocoevalcap",
    "clip",
    "bert-score",
    "selfcheckgpt",
    "torc",
    "torch",
    "torchaudio",
    "torchvision",
    "python-dotenv",
    "tensorflow>=2.12.0",
    "google-genai>=1.28.0",
    "tf-keras>=2.19.0",
    "krippendorff>=0.8.1",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
pycocoevalcap = { git = "https://github.com/jmhessel/pycocoevalcap.git" }
clip = { git = "https://github.com/openai/CLIP.git" }
bert-score = { git = "https://github.com/Accessibility-Research-Collective-UCI/bert_score_with_best_ref.git" }
selfcheckgpt = { git = "https://github.com/Accessibility-Research-Collective-UCI/selfcheckgpt.git" }

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
